---
# tasks file for vlan
- name: recupération des ansibles facts
  debug:
    msg:
      - "{{ ansible_facts.net_hostname }}"

- name: configure interface sw-d1
  ios_config:
    lines:
    - description interface fa0/1 dist-01
    - ip address 172.31.1.1 255.255.255.0
    - no sh
    parents: interface FastEthernet0/1
  when: ansible_facts.net_hostname == "sw-d1"


- name: configure interface sw-d2
  cisco.ios.ios_config:
    lines:
    - description interface fa0/1 dist-02
    - ip address 172.31.1.2 255.255.255.0
    - no sh
    parents: interface FastEthernet0/1
  when: ansible_facts.net_hostname == "sw-d2"
